"""Explicit FIXTURE policy and test-data builders for the portfolio plane.

These are deliberately small, synthetic, labelled ``FIXTURE`` policies —
never investment doctrine, never acceptable for a real run (the engine and
CLI refuse FIXTURE without ``allow_fixture``).
"""

from __future__ import annotations

from typing import Any

from tradehub_research.portfolio.policy import PolicySpec, build_policy
from tradehub_research.portfolio.types import PolicyStatus

FIXTURE_POLICY_VERSION = "fixture-policy-v1"
FIXTURE_SIZING_VERSION = "fixture-sizing-v1"


def fixture_policy_spec() -> dict[str, Any]:
    """The canonical FIXTURE policy spec used across unit tests and RA-03."""
    return {
        "schema_version": 1,
        "eligibility_rules": [
            {
                "rule_id": "watch-on-score-band",
                "priority": 10,
                "from_state": "DISCOVER",
                "to_state": "WATCH",
                "trigger_kind": "SCORE_BAND",
                "conviction_min_ppm": 400000,
                "conviction_max_ppm": 1000000,
                "data_quality_min_ppm": 500000,
                "agreement_min_ppm": 400000,
                "trajectories": ["INITIAL", "RISING", "STABLE"],
                "opportunity_min_ppm": None,
                "opportunity_max_ppm": None,
                "position": "ANY",
                "allowed_sector_coverage_statuses": ["SUPPORTED"],
            },
            {
                "rule_id": "watch-drop",
                "priority": 20,
                "from_state": "WATCH",
                "to_state": "DISCOVER",
                "trigger_kind": "SCORE_BAND",
                "conviction_min_ppm": 0,
                "conviction_max_ppm": 250000,
                "data_quality_min_ppm": 0,
                "agreement_min_ppm": 0,
                "trajectories": ["FALLING", "STABLE"],
                "opportunity_min_ppm": None,
                "opportunity_max_ppm": None,
                "position": "ABSENT",
                "allowed_sector_coverage_statuses": ["SUPPORTED", "LIMITED"],
            },
            {
                "rule_id": "enter-on-band",
                "priority": 30,
                "from_state": "WATCH",
                "to_state": "ENTER",
                "trigger_kind": "SCORE_BAND",
                "conviction_min_ppm": 600000,
                "conviction_max_ppm": 1000000,
                "data_quality_min_ppm": 600000,
                "agreement_min_ppm": 500000,
                "trajectories": ["RISING"],
                "opportunity_min_ppm": 200000,
                "opportunity_max_ppm": None,
                "position": "ABSENT",
                "allowed_sector_coverage_statuses": ["SUPPORTED"],
            },
            {
                "rule_id": "add-on-band",
                "priority": 40,
                "from_state": "HOLD",
                "to_state": "ADD",
                "trigger_kind": "SCORE_BAND",
                "conviction_min_ppm": 700000,
                "conviction_max_ppm": 1000000,
                "data_quality_min_ppm": 600000,
                "agreement_min_ppm": 500000,
                "trajectories": ["RISING"],
                "opportunity_min_ppm": 200000,
                "opportunity_max_ppm": None,
                "position": "PRESENT",
                "allowed_sector_coverage_statuses": ["SUPPORTED"],
            },
            {
                "rule_id": "trim-on-band",
                "priority": 50,
                "from_state": "HOLD",
                "to_state": "TRIM",
                "trigger_kind": "SCORE_BAND",
                "conviction_min_ppm": 0,
                "conviction_max_ppm": 400000,
                "data_quality_min_ppm": 400000,
                "agreement_min_ppm": 400000,
                "trajectories": ["FALLING"],
                "opportunity_min_ppm": None,
                "opportunity_max_ppm": 500000,
                "position": "PRESENT",
                "allowed_sector_coverage_statuses": ["SUPPORTED", "LIMITED"],
            },
            {
                "rule_id": "exit-on-band",
                "priority": 60,
                "from_state": "HOLD",
                "to_state": "EXIT",
                "trigger_kind": "SCORE_BAND",
                "conviction_min_ppm": 0,
                "conviction_max_ppm": 200000,
                "data_quality_min_ppm": 400000,
                "agreement_min_ppm": 400000,
                "trajectories": ["FALLING"],
                "opportunity_min_ppm": None,
                "opportunity_max_ppm": 200000,
                "position": "PRESENT",
                "allowed_sector_coverage_statuses": ["SUPPORTED", "LIMITED"],
            },
            {
                "rule_id": "exit-on-data-integrity",
                "priority": 15,
                "from_state": "HOLD",
                "to_state": "EXIT",
                "trigger_kind": "DATA_INTEGRITY",
                "conviction_min_ppm": 0,
                "conviction_max_ppm": 1000000,
                "data_quality_min_ppm": 0,
                "agreement_min_ppm": 0,
                "trajectories": [],
                "opportunity_min_ppm": None,
                "opportunity_max_ppm": None,
                "position": "PRESENT",
                "allowed_sector_coverage_statuses": ["SUPPORTED", "LIMITED", "RESEARCH_ONLY"],
            },
            {
                "rule_id": "exit-on-policy-ineligible",
                "priority": 16,
                "from_state": "HOLD",
                "to_state": "EXIT",
                "trigger_kind": "POLICY_INELIGIBLE",
                "conviction_min_ppm": 0,
                "conviction_max_ppm": 1000000,
                "data_quality_min_ppm": 0,
                "agreement_min_ppm": 0,
                "trajectories": [],
                "opportunity_min_ppm": None,
                "opportunity_max_ppm": None,
                "position": "PRESENT",
                "allowed_sector_coverage_statuses": ["SUPPORTED", "LIMITED", "RESEARCH_ONLY"],
            },
            {
                "rule_id": "trim-on-risk-reduction",
                "priority": 17,
                "from_state": "HOLD",
                "to_state": "TRIM",
                "trigger_kind": "RISK_REDUCTION",
                "conviction_min_ppm": 0,
                "conviction_max_ppm": 1000000,
                "data_quality_min_ppm": 0,
                "agreement_min_ppm": 0,
                "trajectories": [],
                "opportunity_min_ppm": None,
                "opportunity_max_ppm": None,
                "position": "PRESENT",
                "allowed_sector_coverage_statuses": ["SUPPORTED", "LIMITED"],
            },
            {
                "rule_id": "exit-on-verified-break",
                "priority": 5,
                "from_state": "HOLD",
                "to_state": "EXIT",
                "trigger_kind": "VERIFIED_THESIS_BREAK",
                "conviction_min_ppm": 0,
                "conviction_max_ppm": 1000000,
                "data_quality_min_ppm": 0,
                "agreement_min_ppm": 0,
                "trajectories": [],
                "opportunity_min_ppm": None,
                "opportunity_max_ppm": None,
                "position": "PRESENT",
                "allowed_sector_coverage_statuses": ["SUPPORTED", "LIMITED", "RESEARCH_ONLY"],
            },
            {
                "rule_id": "exit-on-verified-break-trim",
                "priority": 6,
                "from_state": "TRIM",
                "to_state": "EXIT",
                "trigger_kind": "VERIFIED_THESIS_BREAK",
                "conviction_min_ppm": 0,
                "conviction_max_ppm": 1000000,
                "data_quality_min_ppm": 0,
                "agreement_min_ppm": 0,
                "trajectories": [],
                "opportunity_min_ppm": None,
                "opportunity_max_ppm": None,
                "position": "PRESENT",
                "allowed_sector_coverage_statuses": ["SUPPORTED", "LIMITED", "RESEARCH_ONLY"],
            },
        ],
        "transition_controls": {
            "DISCOVER_WATCH": {
                "required_evidence_observations": 0,
                "cooldown_calendar_days": 0,
                "allow_material_change_bypass": False,
                "allow_verified_break_bypass": False,
            },
            "WATCH_DISCOVER": {
                "required_evidence_observations": 0,
                "cooldown_calendar_days": 2,
                "allow_material_change_bypass": False,
                "allow_verified_break_bypass": False,
            },
            "WATCH_ENTER": {
                "required_evidence_observations": 2,
                "cooldown_calendar_days": 0,
                "allow_material_change_bypass": True,
                "allow_verified_break_bypass": False,
            },
            "ENTER_HOLD": {
                "required_evidence_observations": 0,
                "cooldown_calendar_days": 0,
                "allow_material_change_bypass": False,
                "allow_verified_break_bypass": False,
            },
            "HOLD_ADD": {
                "required_evidence_observations": 2,
                "cooldown_calendar_days": 0,
                "allow_material_change_bypass": True,
                "allow_verified_break_bypass": False,
            },
            "HOLD_TRIM": {
                "required_evidence_observations": 2,
                "cooldown_calendar_days": 0,
                "allow_material_change_bypass": True,
                "allow_verified_break_bypass": False,
            },
            "HOLD_EXIT": {
                "required_evidence_observations": 2,
                "cooldown_calendar_days": 0,
                "allow_material_change_bypass": True,
                "allow_verified_break_bypass": True,
            },
            "TRIM_HOLD": {
                "required_evidence_observations": 0,
                "cooldown_calendar_days": 0,
                "allow_material_change_bypass": False,
                "allow_verified_break_bypass": False,
            },
            "TRIM_EXIT": {
                "required_evidence_observations": 2,
                "cooldown_calendar_days": 0,
                "allow_material_change_bypass": True,
                "allow_verified_break_bypass": True,
            },
            "ADD_HOLD": {
                "required_evidence_observations": 0,
                "cooldown_calendar_days": 0,
                "allow_material_change_bypass": False,
                "allow_verified_break_bypass": False,
            },
            "EXIT_WATCH": {
                "required_evidence_observations": 0,
                "cooldown_calendar_days": 2,
                "allow_material_change_bypass": False,
                "allow_verified_break_bypass": False,
            },
        },
        "material_change": {
            "conviction_delta_ppm": 300000,
            "direction_by_edge": {
                "WATCH_ENTER": "UP",
                "HOLD_ADD": "UP",
                "HOLD_TRIM": "DOWN",
                "HOLD_EXIT": "DOWN",
                "TRIM_EXIT": "DOWN",
            },
        },
        "thesis_break": {
            "allowed_verification_methods": ["OWNER_ATTESTED", "DETERMINISTIC_RULE", "FIXTURE"],
            "max_age_calendar_days": 3,
            "realised_opportunity_max_ppm": 0,
            "opportunity_cost_max_ppm": 0,
        },
        "settlement": {
            "quantity_tolerance_microunits": 1000,
            "pending_max_calendar_days": 30,
        },
        "sizing": {
            "sizing_policy_version": FIXTURE_SIZING_VERSION,
            "conviction_bands": [
                {"min_ppm": 700000, "base_target_ppm": 80000},
                {"min_ppm": 600000, "base_target_ppm": 50000},
                {"min_ppm": 0, "base_target_ppm": 0},
            ],
            "quality_bands": [
                {"min_ppm": 700000, "multiplier_ppm": 1000000},
                {"min_ppm": 500000, "multiplier_ppm": 750000},
                {"min_ppm": 0, "multiplier_ppm": 500000},
            ],
            "agreement_bands": [
                {"min_ppm": 700000, "multiplier_ppm": 1000000},
                {"min_ppm": 500000, "multiplier_ppm": 800000},
                {"min_ppm": 0, "multiplier_ppm": 600000},
            ],
            "trajectory_multiplier_ppm": {
                "INITIAL": 700000,
                "RISING": 1000000,
                "FALLING": 600000,
                "STABLE": 800000,
                "REBASED": 600000,
            },
            "trim_remaining_fraction_ppm": 500000,
            "weight_increment_ppm": 1000,
            "min_action_notional_microusd": 1_000_000,
        },
        "risk": {
            "max_position_ppm": 100000,
            "max_sector_ppm": 250000,
            "max_active_signal_book_ppm": 300000,
            "price_stale_calendar_days": 5,
            "return_window_sessions": 30,
            "min_return_observations": 20,
            "volatility_window_sessions": 30,
            "min_vol_observations": 20,
            "annualization_sessions": 252,
            "max_annualized_vol_ppm": 600000,
            "correlation_window_sessions": 60,
            "min_overlap_observations": 30,
            "correlation_threshold_ppm": 700000,
            "max_correlated_book_ppm": 150000,
            "min_correlated_holding_ppm": 20000,
            "adv_window_sessions": 20,
            "min_adv_observations": 15,
            "max_adv_participation_ppm": 100000,
            "max_position_adv_days_ppm": 50000,
            "snapshot_tolerance_ppm": 1000,
            "factor_required": False,
            "drawdown_required": False,
            "unknown_increase": "BLOCK",
            "unknown_decrease": "LIMITED",
        },
        "budget": {
            "timezone": "UTC",
            "max_actionable_count": 3,
            "max_notional_microusd": 5_000_000_000,
            "category_priority": [
                "verified_break",
                "risk_reduction",
                "data_integrity",
                "policy_ineligible",
                "score_band",
            ],
            "reason_priority": [
                "thesis_broken",
                "risk_reduction",
                "data_integrity",
                "policy_ineligible",
                "thesis_realised",
                "opportunity_cost",
            ],
        },
        "order_constraints": {
            "quantity_increment_microunits": 1_000_000,
            "limit_only": True,
        },
    }


def fixture_policy() -> PolicySpec:
    return build_policy(
        FIXTURE_POLICY_VERSION,
        PolicyStatus.FIXTURE,
        fixture_policy_spec(),
    )
